project:
  title: "Python 4 Spatial Analysis - PY4SA"
  type: website
website:
  favicon: img/favico.ico
  twitter-card: true
  site-url: https://mfbenitezp.github.io/PY4SA_Slides/
execute:
  freeze: auto
  